### ISSUE TITLE
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by thierryjanssens** [frubino/mgkit#1]
I have installed mgkit on a new system (in a conda env), but it fails to run with the following error. Did I overlook something?

INFO - mgkit.io.blast: Reading BLAST results from file (barcode02.edit.tab)
| |   #                                                                                                                                                                            | 5511 Elapsed Time: 0:00:00INFO - mgkit.io.blast: Read 6204 BLAST records
| |   #                                                                                                                                                                            | 6203 Elapsed Time: 0:00:00
INFO - mgkit.workflow.filter_gff: Writing to file (barcode02_filter.gff)
INFO - mgkit.io.gff: Loading GFF from file (barcode02.gff)
INFO - mgkit.io.gff: Read 6204 line from file (barcode02.gff)
Traceback (most recent call last):
  File "/home/minion/miniconda3/envs/mgkit/bin/add-gff-info", line 7, in <module>
    from mgkit.workflow.add_gff_info import main
  File "/home/minion/miniconda3/envs/mgkit/lib/python2.7/site-packages/mgkit/workflow/add_gff_info.py", line 220, in <module>
    import pysam
  File "/home/minion/miniconda3/envs/mgkit/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

Kind regards,

Thierry

**Comment by thierryjanssens** [comment]
Solved by making a symlink of libcrypto.so.1.1 to libcrypto.so.1.0.0 in the conda env lib folder.

Thank you.

**Comment by frubino** [comment]
> Solved by making a symlink of libcrypto.so.1.1 to libcrypto.so.1.0.0 in the conda env lib folder.
> 
> Thank you.

Sorry about the late reply, I was away. It seems there is a version mixup with `conda`. The symlink works, but keep in mind that some unexpected errors (probably other import errors) you may encounter may be due to this.
