### ISSUE TITLE
Filter-Gff not working as expected

### ISSUE THREAD

**Issue by TobyBaril** [frubino/mgkit#2]
Hi,

I am trying to use filter-gff to remove overlapping annotations in my gff file, whilst keeping the longest entry. 

The command I am using is:

`filter-gff overlap --progress -v -s 1 -t -d -c -length -a length input.gff output.gff.filtered`

The input file has been sorted using sort -s -k1,1 -k4,4n, so that entries are sorted by scaffold and start coordinate. When I run filter-gff, the output still contains regions that overlap, when I wish to only keep the longest.

Example:

Input:
`sequence_nest   EDTA    helitron        5874    6131    993     -       .       ID=TE_homo_4;Name=TE_00001046;Classification=DNA/Helitron;Sequence_ontology=SO:0000544;Identity=0.79;Method=homology
sequence_nest   EDTA    Mutator_TIR_transposon  5907    6270    736     +       .       ID=TE_homo_5;Name=TE_00001664;Classification=DNA/DTM;Sequence_ontology=SO:0002280;Identity=0.724;Method=homology`

Output:
`sequence_nest   EDTA    helitron        5874    6131    993     -       .       ID=TE_homo_4;Name=TE_00001046;Classification=DNA/Helitron;Sequence_ontology=SO:0000544;Identity=0.79;Method=homology
sequence_nest   EDTA    Mutator_TIR_transposon  5907    6270    736     +       .       ID=TE_homo_5;Name=TE_00001664;Classification=DNA/DTM;Sequence_ontology=SO:0002280;Identity=0.724;Method=homology`

However, my expected output would be:
`sequence_nest   EDTA    Mutator_TIR_transposon  5907    6270    736     +       .       ID=TE_homo_5;Name=TE_00001664;Classification=DNA/DTM;Sequence_ontology=SO:0002280;Identity=0.724;Method=homology`

with the other sequence being shorter and therefore not selected.

Am I doing something wrong in specifying my settings? I wish to filter overlaps regardless of strand, and always wish to keep the longest entry. 

I also tried removing the `-a length` flag, which led to the warning  `mgkit.io.gff.AttributeNotFound: No bitscore attribute found`

Any help you could give me would be great!

Many thanks,

Toby

**Comment by frubino** [comment]
Hi,

apologise for the huge delay. I seem to not have put notifications for the issues. I tried the lines you showed as example. You're right and the problem is a bug where the option to not checking the strand is not used when choosing between annotations.

I am not sure when this was introduced, but I traced it back and it works with this [commit](https://github.com/frubino/mgkit/commit/41a3b0efa89b9eb541f8ebe9b4e452b1d68b9307). This is on the branch 0.6.0, if you need it still.
