### ISSUE TITLE
multithreading

### ISSUE THREAD

**Issue by thierryjanssens** [frubino/mgkit#3]
Dear Francesco,

I was looking around for an argument to set the number of threads utilized, but I could not find any.
Is there a way to parallelize the analyses somehow?

Regards,

Thierry

**Comment by frubino** [comment]
Hi Thierry,

no, I avoided multithreading in general. If you are working with huge GFF or FASTA files, I tend to instead split the GFF files with the script `get-gff-info split`, which makes sure that all annotations of a sequence are in the same file.

When split then I have multiple submissions in the queuing system or a loop in the shell with background jobs. That usually is enough for my workflows. Hope that helps.

Francesco
